<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<PlatformTarget>x64</PlatformTarget>
		<Platforms>x64</Platforms>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AssemblyName>SpatialMorphology</AssemblyName>
		<RootNamespace>SpatialMorphology</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Grasshopper" Version="8.31.26126.13431">
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
		<PackageReference Include="RhinoCommon" Version="8.31.26126.13431">
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Components\Main\" />
	  <Folder Include="Components\Display\" />
	  <Folder Include="Components\Analysis\" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Copy
		  SourceFiles="$(OutputPath)$(AssemblyName).dll"
		  DestinationFiles="$(AppData)\Grasshopper\Libraries\$(AssemblyName).gha" />
	</Target>

</Project>
