<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<Platforms>AnyCPU</Platforms>
		<EnableDynamicLoading>true</EnableDynamicLoading>
		<UseWindowsForms>true</UseWindowsForms>
		<LangVersion>10.0</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AssemblyName>SpatialMorphology</AssemblyName>
		<RootNamespace>SpatialMorphology</RootNamespace>
		<RunPostBuildEvent>Always</RunPostBuildEvent>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Resources\AnalysisStack_24.png" />
	  <None Remove="Resources\CoreLocation_24.png" />
	  <None Remove="Resources\NormalizeValues_24.png" />
	  <None Remove="Resources\ProgramDefinition_24.png" />
	  <None Remove="Resources\SA_Adjacency_24.png" />
	  <None Remove="Resources\SA_Depth_24.png" />
	  <None Remove="Resources\SA_FloorLevel_24.png" />
	  <None Remove="Resources\SA_GeoDist_24.png" />
	  <None Remove="Resources\SA_Isovist_24.png" />
	  <None Remove="Resources\SA_Orientation_24.png" />
	  <None Remove="Resources\SA_Proximity_24.png" />
	  <None Remove="Resources\SA_Solar_24.png" />
	  <None Remove="Resources\SA_ViewAnalysis_24.png" />
	  <None Remove="Resources\SunVectors_24.png" />
	  <None Remove="Resources\ValueSet_24.png" />
	  <None Remove="Resources\VoxelGrid_24.png" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Resources\AnalysisStack_24.png" />
	  <EmbeddedResource Include="Resources\CoreLocation_24.png" />
	  <EmbeddedResource Include="Resources\NormalizeValues_24.png" />
	  <EmbeddedResource Include="Resources\ProgramDefinition_24.png" />
	  <EmbeddedResource Include="Resources\SA_Adjacency_24.png" />
	  <EmbeddedResource Include="Resources\SA_Depth_24.png" />
	  <EmbeddedResource Include="Resources\SA_FloorLevel_24.png" />
	  <EmbeddedResource Include="Resources\SA_GeoDist_24.png" />
	  <EmbeddedResource Include="Resources\SA_Isovist_24.png" />
	  <EmbeddedResource Include="Resources\SA_Orientation_24.png" />
	  <EmbeddedResource Include="Resources\SA_Proximity_24.png" />
	  <EmbeddedResource Include="Resources\SA_Solar_24.png" />
	  <EmbeddedResource Include="Resources\SA_ViewAnalysis_24.png" />
	  <EmbeddedResource Include="Resources\SunVectors_24.png" />
	  <EmbeddedResource Include="Resources\ValueSet_24.png" />
	  <EmbeddedResource Include="Resources\VoxelGrid_24.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Grasshopper" Version="8.31.26126.13431">
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
		<PackageReference Include="RhinoCommon" Version="8.31.26126.13431">
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Components\Display\" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Copy SourceFiles="$(OutputPath)$(AssemblyName).dll" DestinationFiles="$(AppData)\Grasshopper\Libraries\$(AssemblyName).gha" />
	</Target>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <Exec Command="powershell -ExecutionPolicy Bypass -File &quot;$(ProjectDir)deploy.ps1&quot; -Source &quot;$(TargetPath)&quot; -Destination &quot;$(AppData)\Grasshopper\Libraries\$(TargetName).gha&quot;" />
	</Target>

</Project>
